name: OpenMask Python Build
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4
      - name: 安装系统编译依赖
        run: |
          sudo apt update
          sudo apt install -y aapt zipalign apksigner python3 python3-pip
          pip3 install -r requirements.txt
      - name: 启动Python编译
        run: python3 build.py release
      - name: 打包产物上传
        uses: actions/upload-artifact@v4
        with:
          name: OpenMask_Release_APK
          path: out/*
